# Generated by Django 5.2.16 on 2026-07-14 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Aktenzeichen')),
                ('client', models.CharField(max_length=200, verbose_name='Mandant')),
                ('opponent', models.CharField(blank=True, max_length=200, verbose_name='Gegner')),
                ('area_of_law', models.CharField(max_length=100, verbose_name='Rechtsgebiet')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('dormant', 'Ruhend'), ('closed', 'Abgeschlossen')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responisble_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='Verantwortlicher Anwalt')),
            ],
            options={
                'verbose_name': 'Mandat',
                'verbose_name_plural': 'Mandate',
                'ordering': ['-updated_at'],
            },
        ),
    ]
