# Generated by Django 5.2.16 on 2026-07-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='responisble_lawyer',
            new_name='responsible_lawyer',
        ),
    ]
